### ISSUE TITLE
When quickstart and try to login  getting ERROR: relation "users" does not exist

### ISSUE THREAD

**Issue by babkamen** [jprjr/docker-multistreamer#1]

**Comment by jprjr** [comment]
That's no good! Could you provide the output from running `docker-compose up`? The script should initialize the database when it runs

**Comment by babkamen** [comment]
[docker-compose.txt](https://github.com/jprjr/docker-multistreamer/files/905712/docker-compose.txt)

**Comment by babkamen** [comment]
After restarting multistream container everything works. Maybe its good idea to add wait timer for postgress to start 
https://docs.docker.com/compose/startup-order/

**Comment by jprjr** [comment]
Yeah, it's definitely a race-condition kind of thing.

I went ahead and copied the multistreamer sql files into this repo, now when the postgresql container starts, it handles creating the needed tables instead of the multistreamer container.

Try wiping out the needed containers and running docker-compose again, it should work without any problems this time.
